# Generated by Django 2.2.1 on 2019-05-21 15:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('timelord', '0002_auto_20190521_1537'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='day',
            options={'ordering': ['date']},
        ),
        migrations.AlterModelOptions(
            name='scheduleitem',
            options={'ordering': ['start_time']},
        ),
    ]
