# Generated by Django 2.2.1 on 2019-05-24 16:33

from django.db import migrations
from django.contrib.auth.models import Group


def forwards(apps, schema_editor):
    new_group, created = Group.objects.get_or_create(name='public_users')


def backwards(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('rolllistuser', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(forwards, backwards)
    ]
