# Generated by Django 2.2.1 on 2019-05-28 17:09

from django.db import migrations
from django.contrib.auth.models import User


def forwards(apps, schema_editor):
    if not User.objects.filter(email='admin@rolllist.com').exists():
        User.objects.create_superuser(
            username='admin',
            email='admin@rolllist.com',
            password='changeme12345'
        )

def backwards(apps, schema_editor):
    User.objects.filter(email='admin@rolllist.com').delete()

class Migration(migrations.Migration):

    dependencies = [
        ('rolllistuser', '0003_one_to_one_rlu_u'),
    ]

    operations = [
        migrations.RunPython(forwards, backwards)
    ]
