# Generated by Django 2.2.1 on 2019-05-26 17:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rolllist', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='todolist',
            unique_together={('user', 'day')},
        ),
    ]
