# Generated by Django 2.2.1 on 2019-05-22 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rolllist', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='scheduleitem',
            name='recurring',
            field=models.BooleanField(default=False),
        ),
    ]
