# Generated by Django 2.2.1 on 2019-05-30 12:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rolllist', '0003_auto_20190529_1925'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='scheduleitem',
            name='recurrance',
        ),
    ]
