# Generated by Django 2.2.1 on 2019-05-30 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rolllist', '0004_remove_scheduleitem_recurrance'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='todolist',
            name='rolled_over',
        ),
        migrations.AddField(
            model_name='todoitem',
            name='days_incomplete',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='todoitem',
            name='rolled_over',
            field=models.BooleanField(default=False),
        ),
    ]
