# Generated by Django 2.2.1 on 2019-05-30 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rolllist', '0005_adjust_todo_rollover'),
    ]

    operations = [
        migrations.AddField(
            model_name='todoitem',
            name='priority',
            field=models.IntegerField(choices=[(1, 'low'), (2, 'medium'), (3, 'high')], default=1),
        ),
    ]
