# Generated by Django 2.2.1 on 2019-05-30 15:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rolllist', '0006_todoitem_priority'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='todoitem',
            options={'ordering': ['-priority', '-days_incomplete', 'id']},
        ),
    ]
