# Generated by Django 2.2.1 on 2019-05-31 14:12

from django.db import migrations, models
import django.db.models.deletion
import rolllist.models.appmodels


class Migration(migrations.Migration):

    dependencies = [
        ('rolllistuser', '0004_makesuperuser'),
        ('rolllist', '0007_auto_20190530_1535'),
    ]

    operations = [
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(max_length=500)),
                ('day', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rolllist.Day')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rolllistuser.RollListUser')),
            ],
            bases=(models.Model, rolllist.models.appmodels.BaseModel),
        ),
    ]
