# Generated by Django 2.2.1 on 2019-07-08 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rolllist', '0011_scheduleitem_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='day',
            name='_day_of_week',
            field=models.IntegerField(default=11),
            preserve_default=False,
        ),
    ]
