# Generated by Django 2.2.1 on 2019-07-17 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rolllist', '0015_recurring_helptext_and_created'),
    ]

    operations = [
        migrations.AddField(
            model_name='recurringscheduleitem',
            name='all_day',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='scheduleitem',
            name='all_day',
            field=models.BooleanField(default=False),
        ),
    ]
