# Generated by Django 2.2.1 on 2019-07-18 23:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rolllist', '0016_add_all_day_option'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recurringscheduleitem',
            name='location',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='scheduleitem',
            name='location',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
