# Generated by Django 2.2.1 on 2019-08-08 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rolllist', '0017_allow_blank_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='todoitem',
            name='kanban_status',
            field=models.CharField(choices=[('todo', 'To Do'), ('doing', 'Doing'), ('done', 'Done'), ('archived', 'Archived')], db_index=True, default='todo', max_length=10),
        ),
    ]
